class SocketDNSResolver
  @event_queue: Task::Queue

  def self.resolve_host: (String host, ?Integer? deadline) -> String
  def initialize: (String host) -> void
  def resolve: (?Integer? deadline) -> String
  private def __status: () -> Integer
  private def __address: () -> String?
  private def __release: () -> nil
  private def __abandon: () -> nil
end
